server:
  port: 8082
ms.auth.url: {MS.AUTH.URL}
ms.btpmaroc.url: {MS.BTPMAROC.URL}
ms.invoice.url: {MS.INVOICE.URL}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
           # allowedOrigins: "http://34.160.117.160/"
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS

